# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iuxIn9qdISht_pNIPMjd0_Njpe_iBOvN
"""

A=int(input("Enter frist number"))
B=int(input("Enter second number"))
Substraction=A-B
Multipication=A*B
Division=A/B
print("Substracton is:",Substraction)
print("Multipication is:",Multipication)
print("Division is:",Division15
      )