# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X_pFwGAjgmAi6W3RSnUQmfhPweDSnMct
"""

# this is regarding Assignment 2 

import random 

MaxTickits=int(input("Enter number of tickets(make sure to enter integer number only):"))
Peoples=[]

for i in range(MaxTickits):
  name=(input("Enter the name of peoples:-  "))
  Peoples.append(name)
print("All peoples",Peoples)
n=random.randint(0,MaxTickits-1)
print("\n here is our winner",Peoples[n])