# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B51xJt6Fzlio8Owaq-VoRabkEhTdTW8L
"""

N=int(input("enter number:"))
if N>1:
  for i in range(2,N,):
    if (N%i)==0:
      print("Enter numbber is not prime number")
      break
  else:
    print("Enter number is prime number")